//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABM___Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delivery()
        {
            this.Orders1 = new HashSet<Orders>();
        }
    
        public int Id_Driver { get; set; }
        public int Id_Customer { get; set; }
        public Nullable<System.DateTime> Date_of_export { get; set; }
        public Nullable<System.DateTime> Delivery_date { get; set; }
        public int Cost { get; set; }
        public int Id_Ordes { get; set; }
        public int Id_Delivery { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual Orders Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders1 { get; set; }
    }
}
