//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABM___Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SBM_ProjectEntities3 : DbContext
    {
        public SBM_ProjectEntities3()
            : base("name=SBM_ProjectEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Baguette_Products> Baguette_Products { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Delivery> Delivery { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<Factory> Factory { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Store1> Store1 { get; set; }
    }
}
